name: CI 

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[linting]

    - name: Run Ruff linter
      run: |
        ruff check --output-format=github imas_paraview

    - name: Run Ruff formatter
      run: |
        ruff format --diff imas_paraview

  pytest:
    runs-on: ubuntu-latest
    needs: linting
    container:
      image: kitware/paraview-for-ci
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install pip
      run: |
        apt-get update && apt-get install -y python3-pip

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install .[test]

    - name: Run tests
      run: |
        /opt/paraview/install/bin/pvpython -m pytest  --cov=imas_paraview --cov-report=term-missing --cov-report=html --junit-xml=junit-3.11.xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-3.11
        path: htmlcov

  docs:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[docs]

    - name: Build documentation
      run: |
        make -C docs html

    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/_build/html/
        retention-days: 1
